// This is a custom build script for Vercel

// Use CommonJS syntax for better compatibility with Vercel
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

// Run the Vite build command
console.log('🔧 Building frontend with Vite...');
const buildProcess = spawn('npx', ['vite', 'build'], { stdio: 'inherit' });

buildProcess.on('close', (code) => {
  if (code !== 0) {
    console.error('❌ Build failed!');
    process.exit(1);
  }
  
  console.log('✅ Frontend build completed!');
  
  // Create a server.js file that will redirect API requests 
  // to your Replit backend but serve the frontend from Vercel
  console.log('📝 Creating server adapter for Vercel...');
  
  const serverCode = `
// This file is automatically generated during build
// It helps Vercel serve static assets while proxying API requests to Replit

const fs = require('fs');
const path = require('path');

// Define your API endpoint
const API_BACKEND = 'https://zombie-tower3.replit.app';

// Vercel serverless function
module.exports = (req, res) => {
  const { pathname } = new URL(req.url, 'http://localhost');
  
  // If this is an API request, redirect to the Replit backend
  if (pathname.startsWith('/api/')) {
    const apiUrl = API_BACKEND + pathname;
    console.log(\`Proxying API request to: \${apiUrl}\`);
    
    // Redirect to the API endpoint
    res.setHeader('Location', apiUrl);
    res.status(302).end();
    return;
  }
  
  // Otherwise, try to serve a static file
  try {
    // Get file extension to set correct content type
    const ext = path.extname(pathname).toLowerCase();
    
    // Map extensions to content types
    const contentTypes = {
      '.html': 'text/html',
      '.js': 'text/javascript',
      '.css': 'text/css',
      '.json': 'application/json',
      '.png': 'image/png',
      '.jpg': 'image/jpeg',
      '.jpeg': 'image/jpeg',
      '.gif': 'image/gif',
      '.svg': 'image/svg+xml',
    };
    
    // Set the appropriate content type
    if (contentTypes[ext]) {
      res.setHeader('Content-Type', contentTypes[ext]);
    }
    
    // Default to index.html
    const filePath = pathname === '/' 
      ? path.join(__dirname, 'public', 'index.html')
      : path.join(__dirname, 'public', pathname);
    
    // Read and serve the file
    const data = fs.readFileSync(filePath);
    res.status(200).send(data);
  } catch (error) {
    // If file not found, serve index.html (SPA fallback)
    try {
      const indexPath = path.join(__dirname, 'public', 'index.html');
      const indexData = fs.readFileSync(indexPath);
      res.setHeader('Content-Type', 'text/html');
      res.status(200).send(indexData);
    } catch (indexError) {
      res.status(404).send('Not found');
    }
  }
};
`;

  // Write the server adapter file
  fs.mkdirSync('api', { recursive: true });
  fs.writeFileSync(path.join(__dirname, 'api', 'index.js'), serverCode);
  console.log('✅ Server adapter created!');
  
  console.log('🎉 Build process completed successfully!');
});